-- Inserción de los colores
INSERT INTO COLORES_VOLQUETAS (DESCRIPCION_COLOR) VALUES ('Rojo') ;
INSERT INTO COLORES_VOLQUETAS (DESCRIPCION_COLOR) VALUES ('Amarillo') ;
INSERT INTO COLORES_VOLQUETAS (DESCRIPCION_COLOR) VALUES ('Negro') ;
INSERT INTO COLORES_VOLQUETAS (DESCRIPCION_COLOR) VALUES ('Blanclo') ;

SELECT * FROM COLORES_VOLQUETAS;
--
UPDATE COLORES_VOLQUETAS SET DESCRIPCION_COLOR = 'Gris' WHERE DESCRIPCION_COLOR = 'Blanclo';
SELECT * FROM COLORES_VOLQUETAS;

--
DELETE FROM COLORES_VOLQUETAS WHERE ID_COLOR = 3 ;
SELECT * FROM COLORES_VOLQUETAS;
