INSERT INTO CONDUCTORES (ID_CONDUCTOR, NOMBRE, APELLIDO_1, APELLIDO_2, ID_VOLQUETA) VALUES (980872, 'Carlos', 'Pointer', 'Maximus', 'zzz-123') ;
INSERT INTO CONDUCTORES (ID_CONDUCTOR, NOMBRE, APELLIDO_1, APELLIDO_2, ID_VOLQUETA) VALUES (213123, 'Marlon', 'Square', 'Kille', 'qwe-123') ;
INSERT INTO CONDUCTORES (ID_CONDUCTOR, NOMBRE, APELLIDO_1, APELLIDO_2, ID_VOLQUETA) VALUES (112213, 'Jaroll', 'Dominic', 'Praga', 'asd-123') ;


SELECT * FROM CONDUCTORES;
--
UPDATE CONDUCTORES SET APELLIDO_1 = 'Grey' WHERE ID_CONDUCTOR = 980872;
SELECT * FROM COLORES_VOLQUETAS;

--
DELETE FROM CONDUCTORES WHERE ID_CONDUCTOR = 3 ;
SELECT * FROM COLORES_VOLQUETAS;
