INSERT INTO CONDUCTORES VALUES (980872, OBJ_PERSONA('Carlos', 'Pointer', 'Maximus'), 'zzz-123') ;
INSERT INTO CONDUCTORES VALUES (213123, OBJ_PERSONA('Marlon', 'Square', 'Kille'), 'qwe-123') ;
INSERT INTO CONDUCTORES VALUES (112213, OBJ_PERSONA('Jaroll', 'Dominic', 'Praga'), 'asd-123') ;

SELECT C.ID_CONDUCTOR, C.OBJ_PER_CONDUCTOR.NOMBRE, C.OBJ_PER_CONDUCTOR.APELLIDO_1 , C.ID_VOLQUETA AS PLACA, E.NOMBRE AS EMPRESAS
FROM CONDUCTORES C
INNER JOIN VOLQUETAS V ON (C.ID_VOLQUETA = V.PLACA)
INNER JOIN EMPRESAS E ON (V.ID_EMPRESA = E.NIT);
--
UPDATE CONDUCTORES C SET C.OBJ_PER_CONDUCTOR.APELLIDO_1 = 'Grey' WHERE ID_CONDUCTOR = 980872;

SELECT C.ID_CONDUCTOR, C.OBJ_PER_CONDUCTOR.NOMBRE, C.OBJ_PER_CONDUCTOR.APELLIDO_1 , C.ID_VOLQUETA AS PLACA, E.NOMBRE AS EMPRESAS
FROM CONDUCTORES C
INNER JOIN VOLQUETAS V ON (C.ID_VOLQUETA = V.PLACA)
INNER JOIN EMPRESAS E ON (V.ID_EMPRESA = E.NIT);

--
DELETE FROM CONDUCTORES C WHERE C.ID_CONDUCTOR = 3 ;

SELECT C.ID_CONDUCTOR, C.OBJ_PER_CONDUCTOR.NOMBRE, C.OBJ_PER_CONDUCTOR.APELLIDO_1 , C.ID_VOLQUETA AS PLACA, E.NOMBRE AS EMPRESAS
FROM CONDUCTORES C
INNER JOIN VOLQUETAS V ON (C.ID_VOLQUETA = V.PLACA)
INNER JOIN EMPRESAS E ON (V.ID_EMPRESA = E.NIT);
