-- Inserción de las empresas
INSERT INTO EMPRESAS (NIT, NOMBRE) VALUES ('098098098', 'La basurita confiable') ;
INSERT INTO EMPRESAS (NIT, NOMBRE) VALUES ('1233312', 'LimpiaWords S.A.S') ;
INSERT INTO EMPRESAS (NIT, NOMBRE) VALUES ('34344', 'BucketCollectors') ;

SELECT * FROM EMPRESAS;
--
UPDATE EMPRESAS SET NOMBRE = 'BucketCollectors S.A' WHERE NIT = '34344';
SELECT * FROM EMPRESAS;

--
DELETE FROM EMPRESAS WHERE NIT = '1233312' ;
SELECT * FROM EMPRESAS;
