--
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-10-26', 'YYYY-MM-DD'), 0);
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-11-04', 'YYYY-MM-DD'), 0);
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-10-26', 'YYYY-MM-DD'), 0);
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-11-04', 'YYYY-MM-DD'), 0);
UPDATE ENTRADAS SET ID_VENTA = 2 WHERE ID_ENTRADA = 4;

SELECT EN.ID_ENTRADA, EN.FECHA_ENTRADA, EN.ID_VENTA, VE.FECHA_VENTA, VE.VALOR_ENTRADA, VE.CANTIDAD_ENTRADAS AS CANT_ENT_REG_VEN, EN.ID_USUARIO, US.NOMBRE AS NOM_US_REG_ENTR
FROM ENTRADAS EN
INNER JOIN VENTAS_ENTRADAS VE ON EN.ID_VENTA = VE.ID_VENTA
INNER JOIN USUARIOS US ON EN.ID_USUARIO = US.ID_USUARIO;
