--
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-10-26', 'YYYY-MM-DD'), 0);
INSERT INTO ENTRADAS (ID_VENTA, FECHA_ENTRADA, ID_USUARIO) VALUES (1, TO_DATE('2016-11-04', 'YYYY-MM-DD'), 0);
