INSERT INTO MARCAS_VOLQUETAS (NOMBRE_MARCA) VALUES ('Chevrolet') ;
INSERT INTO MARCAS_VOLQUETAS (NOMBRE_MARCA) VALUES ('Audi') ;
INSERT INTO MARCAS_VOLQUETAS (NOMBRE_MARCA) VALUES ('GMC') ;
INSERT INTO MARCAS_VOLQUETAS (NOMBRE_MARCA) VALUES ('Hyunday') ;
INSERT INTO MARCAS_VOLQUETAS (NOMBRE_MARCA) VALUES ('Foton') ;


SELECT * FROM MARCAS_VOLQUETAS;
--
UPDATE MARCAS_VOLQUETAS SET NOMBRE_MARCA = 'Hyundai' WHERE NOMBRE_MARCA = 'Hyunday';
SELECT * FROM MARCAS_VOLQUETAS;

--
DELETE FROM MARCAS_VOLQUETAS WHERE ID_MARCA_VOLQUETA = 3 ;
SELECT * FROM MARCAS_VOLQUETAS;
