INSERT INTO MODELOS_VOLQUETAS (DESCRIPCION_MODELO, ID_MARCA) VALUES ('C-1', 1) ;
INSERT INTO MODELOS_VOLQUETAS (DESCRIPCION_MODELO, ID_MARCA) VALUES ('A-1', 2) ;
INSERT INTO MODELOS_VOLQUETAS (DESCRIPCION_MODELO, ID_MARCA) VALUES ('H-1', 4) ;
INSERT INTO MODELOS_VOLQUETAS (DESCRIPCION_MODELO, ID_MARCA) VALUES ('F-1', 5) ;


SELECT MODELOS_VOLQUETAS.ID_MODELO, MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA FROM MODELOS_VOLQUETAS INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA);

--
UPDATE MODELOS_VOLQUETAS SET DESCRIPCION_MODELO = 'H-2' WHERE ID_MODELO = 4;
SELECT MODELOS_VOLQUETAS.ID_MODELO, MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA FROM MODELOS_VOLQUETAS INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA);


--
DELETE FROM MODELOS_VOLQUETAS WHERE ID_MODELO = 3 ;
SELECT MODELOS_VOLQUETAS.ID_MODELO, MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA FROM MODELOS_VOLQUETAS INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA);
