--
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS, ID_USUARIO) VALUES ('zzz-123', TO_DATE('2016-02-21', 'YYYY-MM-DD'), 25000, 2, 0);
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS, ID_USUARIO) VALUES ('qwe-123', TO_DATE('2016-05-15', 'YYYY-MM-DD'), 25000, 20, 0);
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS, ID_USUARIO) VALUES ('asd-123', TO_DATE('2016-03-2', 'YYYY-MM-DD'), 25000, 12, 0);

--
SELECT VE.ID_VOLQUETA AS PLACA, EM.NOMBRE AS EMPRESA, VE.FECHA_VENTA, VE.VALOR_ENTRADA, VE.CANTIDAD_ENTRADAS, VE.ID_USUARIO, US.OBJ_PERSONA_USUARIO.NOMBRE AS NOMBRE_USUARIO
FROM VENTAS_ENTRADAS VE
INNER JOIN VOLQUETAS VO ON (VE.ID_VOLQUETA = VO.PLACA)
INNER JOIN EMPRESAS EM ON (VO.ID_EMPRESA = EM.NIT)
INNER JOIN USUARIOS US ON (VE.ID_USUARIO = US.ID_USUARIO);

--
UPDATE VENTAS_ENTRADAS SET CANTIDAD_ENTRADAS = 4 WHERE ID_VENTA = 1;

SELECT VE.ID_VOLQUETA AS PLACA, EM.NOMBRE AS EMPRESA, VE.FECHA_VENTA, VE.VALOR_ENTRADA, VE.CANTIDAD_ENTRADAS, VE.ID_USUARIO, US.OBJ_PERSONA_USUARIO.NOMBRE AS NOMBRE_USUARIO
FROM VENTAS_ENTRADAS VE
INNER JOIN VOLQUETAS VO ON (VE.ID_VOLQUETA = VO.PLACA)
INNER JOIN EMPRESAS EM ON (VO.ID_EMPRESA = EM.NIT)
INNER JOIN USUARIOS US ON (VE.ID_USUARIO = US.ID_USUARIO);
