--
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS) VALUES ('zzz-123', TO_DATE('2016-02-21', 'YYYY-MM-DD'), 25000, 2);
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS) VALUES ('qwe-123', TO_DATE('2016-05-15', 'YYYY-MM-DD'), 25000, 20);
INSERT INTO VENTAS_ENTRADAS (ID_VOLQUETA, FECHA_VENTA, VALOR_ENTRADA, CANTIDAD_ENTRADAS) VALUES ('asd-123', TO_DATE('2016-03-2', 'YYYY-MM-DD'), 25000, 12);

--
SELECT * FROM VENTAS_ENTRADAS;

--
UPDATE VENTAS_ENTRADAS SET CANTIDAD_ENTRADAS = 4 WHERE ID_VENTA = 1;
SELECT * FROM VENTAS_ENTRADAS;
