--
INSERT INTO VOLQUETAS (PLACA, ID_COLOR, ID_MODELO, ID_EMPRESA) VALUES ('zzz-123', 1, 1, '098098098');
INSERT INTO VOLQUETAS (PLACA, ID_COLOR, ID_MODELO, ID_EMPRESA) VALUES ('qwe-123', 2, 1, '098098098');
INSERT INTO VOLQUETAS (PLACA, ID_COLOR, ID_MODELO, ID_EMPRESA) VALUES ('asd-123', 1, 2, '098098098');
INSERT INTO VOLQUETAS (PLACA, ID_COLOR, ID_MODELO, ID_EMPRESA) VALUES ('asq-123', 2, 2, '098098098');

--
SELECT VOLQUETAS.PLACA, COLORES_VOLQUETAS.DESCRIPCION_COLOR , MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA, EMPRESAS.NOMBRE
FROM VOLQUETAS
INNER JOIN COLORES_VOLQUETAS ON (VOLQUETAS.ID_COLOR = COLORES_VOLQUETAS.ID_COLOR)
INNER JOIN MODELOS_VOLQUETAS ON (VOLQUETAS.ID_MODELO = MODELOS_VOLQUETAS.ID_MODELO)
INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA)
INNER JOIN EMPRESAS ON (VOLQUETAS.ID_EMPRESA = EMPRESAS.NIT) ;

--
UPDATE VOLQUETAS SET ID_EMPRESA = '34344' WHERE PLACA = 'asd-123';

SELECT VOLQUETAS.PLACA, COLORES_VOLQUETAS.DESCRIPCION_COLOR , MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA, EMPRESAS.NOMBRE
FROM VOLQUETAS
INNER JOIN COLORES_VOLQUETAS ON (VOLQUETAS.ID_COLOR = COLORES_VOLQUETAS.ID_COLOR)
INNER JOIN MODELOS_VOLQUETAS ON (VOLQUETAS.ID_MODELO = MODELOS_VOLQUETAS.ID_MODELO)
INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA)
INNER JOIN EMPRESAS ON (VOLQUETAS.ID_EMPRESA = EMPRESAS.NIT) ;

--
DELETE FROM VOLQUETAS WHERE PLACA = 'asq-123' ;

SELECT VOLQUETAS.PLACA, COLORES_VOLQUETAS.DESCRIPCION_COLOR , MODELOS_VOLQUETAS.DESCRIPCION_MODELO, MARCAS_VOLQUETAS.NOMBRE_MARCA, EMPRESAS.NOMBRE
FROM VOLQUETAS
INNER JOIN COLORES_VOLQUETAS ON (VOLQUETAS.ID_COLOR = COLORES_VOLQUETAS.ID_COLOR)
INNER JOIN MODELOS_VOLQUETAS ON (VOLQUETAS.ID_MODELO = MODELOS_VOLQUETAS.ID_MODELO)
INNER JOIN MARCAS_VOLQUETAS ON (MODELOS_VOLQUETAS.ID_MARCA = MARCAS_VOLQUETAS.ID_MARCA_VOLQUETA)
INNER JOIN EMPRESAS ON (VOLQUETAS.ID_EMPRESA = EMPRESAS.NIT) ;
