DROP TABLE COLORES_VOLQUETAS CASCADE CONSTRAINTS ;

CREATE TABLE COLORES_VOLQUETAS
  (
    ID_COLOR          NUMBER (15) ,
    DESCRIPCION_COLOR VARCHAR2 (30)
  );
ALTER TABLE COLORES_VOLQUETAS ADD CONSTRAINT COLORES_VOLQUETAS_PK PRIMARY KEY ( ID_COLOR ) ;
ALTER TABLE COLORES_VOLQUETAS ADD CONSTRAINT COLORES_VOLQUETAS_DES_NN CHECK (DESCRIPCION_COLOR IS NOT NULL) ;
