DROP TABLE MARCAS_VOLQUETAS CASCADE CONSTRAINTS ;

CREATE TABLE MARCAS_VOLQUETAS
  (
    ID_MARCA_VOLQUETA NUMBER (15),
    NOMBRE_MARCA      VARCHAR2 (20)
  );
ALTER TABLE MARCAS_VOLQUETAS ADD CONSTRAINT MARCAS_VOLQUETAS_PK PRIMARY KEY ( ID_MARCA_VOLQUETA ) ;
ALTER TABLE MARCAS_VOLQUETAS ADD CONSTRAINT MARCAS_VOLQUETAS_NOMBRE_NN CHECK (NOMBRE_MARCA IS NOT NULL) ;
