DROP TABLE MODELOS_VOLQUETAS CASCADE CONSTRAINTS ;

CREATE TABLE MODELOS_VOLQUETAS
  (
    ID_MODELO          NUMBER  ,
    DESCRIPCION_MODELO VARCHAR2 (25) ,
    ID_MARCA           NUMBER (25)
  ) ;
ALTER TABLE MODELOS_VOLQUETAS ADD CONSTRAINT MODELOS_VOLQUETAS_PK PRIMARY KEY ( ID_MODELO ) ;
ALTER TABLE MODELOS_VOLQUETAS ADD CONSTRAINT MODELOS_VOLQUETAS_DSC_MDL_NN CHECK ( DESCRIPCION_MODELO IS NOT NULL) ;
ALTER TABLE MODELOS_VOLQUETAS ADD CONSTRAINT MODELOS_VOLQUETAS_MAR_VLQ_FK FOREIGN KEY ( ID_MARCA ) REFERENCES MARCAS_VOLQUETAS ( ID_MARCA_VOLQUETA ) ;
