DROP TABLE USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS
  (
    ID_USUARIO NUMBER (10) ,
    OBJ_PERSONA_USUARIO OBJ_PERSONA,
    CONTRASENA VARCHAR2 (30)
  ) ;

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( ID_USUARIO ) ;
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_NOMBRE_NN CHECK ( OBJ_PERSONA_USUARIO.NOMBRE IS NOT NULL );
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_APELLIDO_NN CHECK ( OBJ_PERSONA_USUARIO.APELLIDO_1 IS NOT NULL );
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_CONTRASENA_NN CHECK ( CONTRASENA IS NOT NULL )
