DROP TABLE VENTAS_ENTRADAS CASCADE CONSTRAINTS ;

CREATE TABLE VENTAS_ENTRADAS
  (
    ID_VENTA          NUMBER (25) ,
    ID_VOLQUETA       VARCHAR2 (10) ,
    FECHA_VENTA       DATE ,
    VALOR_ENTRADA     NUMBER (8) ,
    CANTIDAD_ENTRADAS NUMBER (5)
  ) ;

ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_PK PRIMARY KEY ( ID_VENTA ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_ID_VOL_NN CHECK ( ID_VOLQUETA IS NOT NULL ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_FECHA_VEN_NN CHECK ( FECHA_VENTA IS NOT NULL ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_VALOR_v CHECK ( VALOR_ENTRADA >= 1 ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_CANTIDAD_ENTRADAS_V CHECK ( CANTIDAD_ENTRADAS >= 1 ) ;

ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_ENTRADAS_VOLQUETAS_FK FOREIGN KEY ( ID_VOLQUETA ) REFERENCES VOLQUETAS ( PLACA ) ;
