DROP TABLE VENTAS_ENTRADAS CASCADE CONSTRAINTS ;

CREATE TABLE VENTAS_ENTRADAS
  (
    ID_VENTA          NUMBER (25) NOT NULL ,
    ID_VOLQUETA       VARCHAR2 (10) NOT NULL ,
    FECHA_VENTA       DATE NOT NULL ,
    VALOR_ENTRADA     NUMBER (8) NOT NULL ,
    CANTIDAD_ENTRADAS NUMBER (5) NOT NULL ,
    ID_USUARIO        NUMBER (10) NOT NULL
  ) ;

ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_PK PRIMARY KEY ( ID_VENTA ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_ID_VOL_NN CHECK ( ID_VOLQUETA IS NOT NULL ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_FECHA_VEN_NN CHECK ( FECHA_VENTA IS NOT NULL ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_VALOR_v CHECK ( VALOR_ENTRADA >= 1 ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_CANTIDAD_ENTRADAS_V CHECK ( CANTIDAD_ENTRADAS >= 1 ) ;

ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_ENTRADAS_VOLQUETAS_FK FOREIGN KEY ( ID_VOLQUETA ) REFERENCES VOLQUETAS ( PLACA ) ;
ALTER TABLE VENTAS_ENTRADAS ADD CONSTRAINT VENTAS_ENTRADAS_USUARIOS_FK FOREIGN KEY ( ID_USUARIO ) REFERENCES USUARIOS ( ID_USUARIO ) ;
