DROP TABLE VOLQUETAS CASCADE CONSTRAINTS;

CREATE TABLE VOLQUETAS
  (
    PLACA      VARCHAR2 (10) NOT NULL ,
    ID_COLOR   NUMBER (15) NOT NULL ,
    ID_MODELO  NUMBER (15) NOT NULL ,
    ID_EMPRESA VARCHAR2 (25) NOT NULL
  ) ;

ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_PK  PRIMARY KEY ( PLACA ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_COLORES_VOLQUETAS_FK FOREIGN KEY ( ID_COLOR ) REFERENCES COLORES_VOLQUETAS ( ID_COLOR ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_ID_COLOR_NN CHECK ( ID_COLOR IS NOT NULL ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_MODELO_FK FOREIGN KEY ( ID_MODELO ) REFERENCES MODELOS_VOLQUETAS ( ID_MODELO ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_ID_MODELO CHECK ( ID_MODELO IS NOT NULL ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_EMPRESAS_FK FOREIGN KEY ( ID_EMPRESA ) REFERENCES EMPRESAS ( NIT ) ;
ALTER TABLE VOLQUETAS ADD CONSTRAINT VOLQUETAS_ID_EMPRESA CHECK ( ID_EMPRESA IS NOT NULL ) ;
