@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/ESQUEMA.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/EMPRESAS.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/COLORES_VOLQUETAS.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/MARCAS_VOLQUETAS.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/MODELOS_VOLQUETAS.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/VOLQUETAS.sql'
@ '/home/sebastian/Documentos/BD2/bd-2-ud/SCRIPTS/DDL/CONDUCTORES.sql'
