DROP SEQUENCE SEQ_COLORES_VOLQUETAS;

CREATE SEQUENCE SEQ_COLORES_VOLQUETAS
increment by 1
start with 1
nocache
nocycle;


CREATE OR REPLACE TRIGGER TR_COLORES_VOLQUETAS
BEFORE INSERT ON COLORES_VOLQUETAS
FOR EACH ROW
BEGIN
  SELECT SEQ_COLORES_VOLQUETAS.nextval
  INTO :new.ID_COLOR
  FROM dual;
END;
/
