DROP SEQUENCE SEQ_ENTRADAS;

set serveroutput on;


CREATE SEQUENCE SEQ_ENTRADAS
increment by 1
start with 1
nocache
nocycle;

CREATE OR REPLACE TRIGGER TR_ENTRADAS
FOR INSERT OR UPDATE ON ENTRADAS
COMPOUND TRIGGER
  CANT_ENT_REG NUMBER;
  CANT_ENT_VEN NUMBER;
  CANTIDAD_ENTRADAS_E EXCEPTION;
  FECHA_VENTA_E EXCEPTION;

-- BEFORE STATEMENT IS
--   BEGIN
--     SELECT COUNT(*)
--     INTO CANT_ENT_REG
--     FROM ENTRADAS
--     WHERE ID_VENTA = :new.ID_VENTA;
-- END BEFORE STATEMENT;

BEFORE EACH ROW IS
  BEGIN
  SELECT COUNT(*)
  INTO CANT_ENT_REG
  FROM ENTRADAS
  WHERE ID_VENTA = :new.ID_VENTA;
    IF (:new.FECHA_ENTRADA > SYSDATE) THEN
      RAISE FECHA_VENTA_E;
    END IF;
    IF INSERTING THEN

      SELECT (CANTIDAD_ENTRADAS)
      INTO CANT_ENT_VEN
      FROM VENTAS_ENTRADAS
      WHERE ID_VENTA = :new.ID_VENTA;

      IF (CANT_ENT_REG >= CANT_ENT_VEN) THEN
        RAISE CANTIDAD_ENTRADAS_E;
      END IF;

      SELECT SEQ_ENTRADAS.nextval
      INTO :new.ID_ENTRADA
      FROM dual;
    ELSIF UPDATING THEN
      SELECT COUNT(*)
      INTO CANT_ENT_REG
      FROM ENTRADAS
      WHERE ID_VENTA = :new.ID_VENTA;

      SELECT (CANTIDAD_ENTRADAS)
      INTO CANT_ENT_VEN
      FROM VENTAS_ENTRADAS
      WHERE ID_VENTA = :new.ID_VENTA;

      IF (CANT_ENT_REG >= CANT_ENT_VEN) THEN
        RAISE CANTIDAD_ENTRADAS_E;
      END IF;
    END IF;
  EXCEPTION
    WHEN CANTIDAD_ENTRADAS_E THEN
      raise_application_error(-20000,'No se puede registrar la entrada, lo volqueta no tiene mas cupos de entradas');
    WHEN FECHA_VENTA_E THEN
      raise_application_error(-20002,'La fecha de la entrada no puede ser mayor a la fecha actual');
  END BEFORE EACH ROW;
END TR_ENTRADAS;
/
