DROP SEQUENCE SEQ_MARCAS_VOLQUETAS;

CREATE SEQUENCE SEQ_MARCAS_VOLQUETAS
increment by 1
start with 1
nocache
nocycle;

CREATE OR REPLACE TRIGGER TR_MARCAS_VOLQUETAS
BEFORE INSERT ON MARCAS_VOLQUETAS
FOR EACH ROW
BEGIN
  SELECT SEQ_MARCAS_VOLQUETAS.nextval
  INTO :new.ID_MARCA_VOLQUETA
  FROM dual;
END;
/
