DROP SEQUENCE SEQ_VENTAS_ENTRADAS;

CREATE SEQUENCE SEQ_VENTAS_ENTRADAS
increment by 1
start with 1
nocache
nocycle;

CREATE OR REPLACE TRIGGER TR_VENTAS_ENTRADAS
BEFORE INSERT OR UPDATE ON VENTAS_ENTRADAS
FOR EACH ROW
DECLARE
  FECHA_VENTA_E EXCEPTION;
BEGIN
  IF (:new.FECHA_VENTA > SYSDATE) THEN
    RAISE FECHA_VENTA_E;
  END IF;
  IF INSERTING THEN
    SELECT SEQ_VENTAS_ENTRADAS.nextval
    INTO :new.ID_VENTA
    FROM dual;
  END IF;
EXCEPTION
  WHEN FECHA_VENTA_E THEN
  raise_application_error(-20001,'La fecha de la venta no puede ser mayor a la fecha actual');
END;
/
