DROP SEQUENCE SEQ_VENTAS_ENTRADAS;

CREATE SEQUENCE SEQ_VENTAS_ENTRADAS
increment by 1
start with 1
nocache
nocycle;

CREATE OR REPLACE TRIGGER TR_VENTAS_ENTRADAS
BEFORE INSERT ON VENTAS_ENTRADAS
FOR EACH ROW
BEGIN
  SELECT SEQ_VENTAS_ENTRADAS.nextval
  INTO :new.ID_VENTA
  FROM dual;
END;
/
